### ISSUE TITLE
OpenAI claims that GPT4o good in reading full context but this test show opposite

### ISSUE THREAD

**Issue by albertaleksieiev** [llmonpy/needle-in-a-needlestack#4]
Note: This is not an issue of this repo, but just a question. 

According to [release doc](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/) they claiming - ..._GPT-4o mini enables a broad range of tasks with its low cost and latency, such as ... and pass a large volume of context to the model (e.g., full code base or conversation history)_

But it has the [same problem as all models](https://github.com/llmonpy/needle-in-a-needlestack/blob/main/docs/gpt4o-mini.md) - it works bad for pay attention in the middle of context message, But `GPT 4o` don't have this problem. For working with large code base or conversation history you need to pass `NIAH` test. Isn it?

| ![image](https://github.com/user-attachments/assets/cb1bab7f-8cb5-44dd-ac10-60ea43bd296a) | ![image](https://github.com/user-attachments/assets/1b65eaac-bb40-4090-938e-61baa8bae712)
|:----------------------------------:|:---------------------------------------:|
|       gpt-4o       |               gpt-4o-mini               |

**Comment by sftombu** [comment]
GPT4o is great at using its context -- refer to the graph on the right.  GPT4o-mini is not that great at using its context window though.
